id: P5A451903
initial_creation_type: ocr
source_metadata:
  volumes:
    c14b16607f3e43babe94bf1665301e7c:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: རང་གི་བྱ་བའི་རིམ་པ་བསྐུལ་བ་དང་བཅས་པ་ཡི་གེར་བྲིས་པ།
      total_pages: 1902
      volume_number: 64
