id: D8084E8DB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T13:59:24+00:00'
last_modified: '2022-05-27T15:35:15.196912+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '9497':
      image_group_id: I1PD95909
      title: རང་གི་བྱ་བའི་རིམ་པ་བསྐུལ་བ་དང་བཅས་པ་ཡི་གེར་བྲིས་པ།
      total_pages: 1902
      order: 64
      base_file: 9497.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
